package com.quranreader.custom.data.local.ayahinfo

import androidx.room.Database
import androidx.room.RoomDatabase

/**
 * Read-only Room database backed by the bundled SQLite asset
 * `assets/quran_data/ayahinfo.db`. This database contains the per-glyph
 * pixel coordinates for the 604 mushaf page images shipped at
 * `assets/mushaf_pages/page_<NNN>.webp` (width = 1024 px). It is the
 * **only** quran-content database left in the app: text rendering is
 * done from the page images, not from a text database.
 *
 * The bundled DB is regenerated by `tools/build_mushaf_pages.py`.
 */
@Database(
    entities = [GlyphEntity::class],
    version = 1,
    exportSchema = false,
)
abstract class AyahInfoDatabase : RoomDatabase() {
    abstract fun glyphDao(): GlyphDao

    companion object {
        const val DB_NAME = "ayahinfo.db"
        const val DB_ASSET_PATH = "quran_data/ayahinfo.db"
        /** Native pixel width of every bundled page image. */
        const val IMAGE_WIDTH_PX = 1024
        /** Native pixel height of every bundled page image. */
        const val IMAGE_HEIGHT_PX = 1656
    }
}
