package com.quranreader.custom.ui.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.quranreader.custom.data.QuranNavigationData
import com.quranreader.custom.data.local.ayahinfo.AyahInfoRepository
import com.quranreader.custom.data.model.SurahInfo
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import javax.inject.Inject

/**
 * Backs the **Find Verse** popup dialog — the only search surface in
 * the app. The dialog is a guided two-stage form:
 *
 *  1. Pick a Surah from a filterable list of all 114 surahs.
 *  2. Type the ayah number, validated against the bundled Quran
 *     metadata so the user can never request an out-of-range verse.
 *
 * On submit we resolve the page from the bundled `ayahinfo.db` (the
 * per-glyph coordinate table generated by the Python
 * `quran/ayah-detection` pipeline) and emit a one-shot navigation
 * event so the dialog's host can dismiss the popup and jump to the
 * reader with the verse pre-highlighted.
 */
@HiltViewModel
class SearchViewModel @Inject constructor(
    private val ayahInfoRepository: AyahInfoRepository,
) : ViewModel() {

    /** All 114 surahs with metadata used by the picker filter. */
    val surahCatalog: List<SurahInfo> = QuranNavigationData.surahList

    private val _ayahPickerQuery = MutableStateFlow("")
    val ayahPickerQuery: StateFlow<String> = _ayahPickerQuery.asStateFlow()

    /** Surahs visible in the picker, filtered by [ayahPickerQuery]. */
    val filteredSurahs: StateFlow<List<SurahInfo>> = _ayahPickerQuery
        .map { q -> matchSurahs(q) }
        .stateIn(viewModelScope, SharingStarted.Eagerly, surahCatalog)

    private val _selectedSurah = MutableStateFlow<SurahInfo?>(null)
    val selectedSurah: StateFlow<SurahInfo?> = _selectedSurah.asStateFlow()

    private val _ayahInput = MutableStateFlow("")
    val ayahInput: StateFlow<String> = _ayahInput.asStateFlow()

    /** Non-null only when the current input is invalid. */
    private val _ayahError = MutableStateFlow<AyahInputError?>(null)
    val ayahError: StateFlow<AyahInputError?> = _ayahError.asStateFlow()

    private val _isResolvingAyah = MutableStateFlow(false)
    val isResolvingAyah: StateFlow<Boolean> = _isResolvingAyah.asStateFlow()

    /** One-shot navigation events for the dialog host to consume. */
    private val _events = MutableSharedFlow<SearchEvent>(replay = 0)
    val events: SharedFlow<SearchEvent> = _events.asSharedFlow()

    fun updateAyahPickerQuery(query: String) {
        _ayahPickerQuery.value = query
    }

    fun selectSurah(surah: SurahInfo) {
        _selectedSurah.value = surah
        _ayahPickerQuery.value = ""
        // Re-validate any pending ayah text against the new max so the
        // helper text and submit button update immediately.
        validateAyahInput(_ayahInput.value, surah)
    }

    fun clearSelectedSurah() {
        _selectedSurah.value = null
        _ayahInput.value = ""
        _ayahError.value = null
    }

    /**
     * Reset the entire dialog state. Called when the host dismisses
     * the popup so reopening it starts fresh.
     */
    fun resetForReopen() {
        _ayahPickerQuery.value = ""
        _selectedSurah.value = null
        _ayahInput.value = ""
        _ayahError.value = null
        _isResolvingAyah.value = false
    }

    /**
     * Update the typed ayah string. Strips non-digits and clamps the
     * length to 3 chars so the picker always carries a clean number,
     * then validates against the selected surah's max so the helper
     * text / submit button reflect the latest state.
     */
    fun updateAyahInput(raw: String) {
        val digitsOnly = raw.filter(Char::isDigit).take(3)
        _ayahInput.value = digitsOnly
        validateAyahInput(digitsOnly, _selectedSurah.value)
    }

    private fun validateAyahInput(text: String, surah: SurahInfo?) {
        if (surah == null) {
            _ayahError.value = if (text.isBlank()) null else AyahInputError.NoSurahSelected
            return
        }
        if (text.isBlank()) {
            _ayahError.value = null
            return
        }
        val n = text.toIntOrNull()
        _ayahError.value = when {
            n == null -> AyahInputError.NotANumber
            n < 1 -> AyahInputError.BelowMin
            n > surah.ayahCount -> AyahInputError.AboveMax(surah.ayahCount)
            else -> null
        }
    }

    /**
     * Submit the surah + ayah, resolve the mushaf page from the
     * bundled ayah-info DB, and emit a navigation event. Refuses to
     * submit while validation is unhappy or already in flight.
     */
    fun submitAyahLookup() {
        val surah = _selectedSurah.value ?: run {
            _ayahError.value = AyahInputError.NoSurahSelected
            return
        }
        val ayah = _ayahInput.value.toIntOrNull() ?: run {
            _ayahError.value = AyahInputError.NotANumber
            return
        }
        if (ayah !in 1..surah.ayahCount) {
            _ayahError.value = AyahInputError.AboveMax(surah.ayahCount)
            return
        }
        if (_isResolvingAyah.value) return
        _isResolvingAyah.value = true
        viewModelScope.launch {
            try {
                // Room suspend DAOs already pick a background dispatcher,
                // but the rest of the data-layer in this codebase
                // explicitly hops onto IO for DB calls — keep the same
                // discipline so reviewers don't have to remember which
                // call site is implicit and which is explicit.
                val page = withContext(Dispatchers.IO) {
                    ayahInfoRepository.pageForAyah(surah.number, ayah)
                }
                if (page != null && page in 1..604) {
                    _events.emit(SearchEvent.NavigateToAyah(page, surah.number, ayah))
                } else {
                    // Should be unreachable for valid ayah numbers, but
                    // we surface a friendly error so a corrupt asset
                    // doesn't silently swallow the user's request.
                    _ayahError.value = AyahInputError.NotFound
                }
            } finally {
                _isResolvingAyah.value = false
            }
        }
    }

    private fun matchSurahs(query: String): List<SurahInfo> {
        val q = query.trim().lowercase()
        if (q.isBlank()) return surahCatalog
        return surahCatalog.filter { s ->
            s.number.toString() == q ||
                s.englishName.lowercase().contains(q) ||
                s.arabicName.contains(query)
        }
    }
}

/**
 * Validation outcomes for the ayah-input field. Every variant maps to
 * a localised string in the dialog — the dialog owns the copy so the
 * ViewModel stays free of `Context`.
 */
sealed interface AyahInputError {
    object NoSurahSelected : AyahInputError
    object NotANumber : AyahInputError
    object BelowMin : AyahInputError
    /** [max] is the surah's verified ayah count (e.g. 286 for Al-Baqarah). */
    data class AboveMax(val max: Int) : AyahInputError
    object NotFound : AyahInputError
}

/** One-shot events surfaced by the ViewModel and consumed by the dialog. */
sealed interface SearchEvent {
    data class NavigateToAyah(val page: Int, val surah: Int, val ayah: Int) : SearchEvent
}
