package com.quranreader.custom.data.memorization

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

/**
 * DAO for the `memorization_sessions` table.
 */
@Dao
interface MemorizationSessionDao {

    /** Insert a new session, returning the autogenerated row id. */
    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insert(session: MemorizationSession): Long

    /** Update an existing row (e.g. mark completed, save mid-progress). */
    @Update
    suspend fun update(session: MemorizationSession)

    /** Stream all sessions, most recent first. */
    @Query("SELECT * FROM memorization_sessions ORDER BY startedAt DESC")
    fun observeAll(): Flow<List<MemorizationSession>>

    /** Look up a session by id (used for resume). */
    @Query("SELECT * FROM memorization_sessions WHERE id = :id LIMIT 1")
    suspend fun getById(id: Long): MemorizationSession?

    /** Streams the in-progress session (completedAt is null), if any. */
    @Query("SELECT * FROM memorization_sessions WHERE completedAt IS NULL ORDER BY startedAt DESC LIMIT 1")
    fun observeInProgress(): Flow<MemorizationSession?>

    @Query("DELETE FROM memorization_sessions WHERE id = :id")
    suspend fun delete(id: Long)
}
